### ISSUE TITLE
rustls::ServerCertVerifier should check remote_public_key

### ISSUE THREAD

**Issue by kpp** [ipfs-rust/libp2p-quic#7]
https://github.com/ipfs-rust/libp2p-quic/blob/f2a860282288138128a6aecc14eb9b96df924a9a/src/crypto.rs#L117

According to https://github.com/libp2p/specs/blob/master/tls/tls.md#libp2p-public-key-extension, the given `remote_public_key` should be checked inside `ServerCertVerifier::verify_server_cert` against `Libp2pExtension::peer_key`:

> The public host key allows the peer to calculate the peer ID of the peer it is connecting to. Clients MUST verify that the peer ID derived from the certificate matches the peer ID they intended to connect to, and MUST abort the connection if there is a mismatch.

**Comment by dvc94ch** [comment]
the swarm checks that the peer ids match, the transport returns the `PeerId` and the `StreamMuxerBox`. we don't know the `remote_public_key` here yet as the peer hasn't sent it to us. in the noise protocol it is used to support 0-rtt encryption, which the tls version does not. we can do this because the noise protocol only supports ed25519 keys, which means that the `PeerId` contains the `PublicKey` instead of the hash of the public key like would happen with rsa keys.

**Comment by dvc94ch** [comment]
well actually I'm a bit confused on that one. the core/swarm code isn't exactly easy to read. @mxinden can you point me to where the swarm checks the peer_id when dialing another peer?

**Comment by dvc94ch** [comment]
so looks like you're right. the dialer should close the connection if the peer id doesn't match.

**Comment by kpp** [comment]
> can you point me to where the swarm checks the peer_id when dialing another peer?

https://github.com/libp2p/go-libp2p-tls/blob/7530faa07acbfc0aa918c072c2cb35d3c8d5d859/crypto.go#L100

**Comment by dvc94ch** [comment]
I meant in the rust version. Did you see the added tests that ensure that the public key is checked?

**Comment by dvc94ch** [comment]
So the question is not if it needs to be checked, it certainly does. The question is if other code is already checking it. While I didn't find exactly where it is checked the tests in #7 show that it is checked.

**Comment by kpp** [comment]
Thank you!

**Comment by mxinden** [comment]
> well actually I'm a bit confused on that one. the core/swarm code isn't exactly easy to read. @mxinden can you point me to where the swarm checks the peer_id when dialing another peer?

@dvc94ch peer id validation is happening here:

https://github.com/libp2p/rust-libp2p/blob/68b5f743ad8de8f1dd3c96439e7ffed7825e3cef/core/src/connection/pool.rs#L322-L344
